apiVersion: apps/v1
kind: Deployment
metadata:
  name: jkpgcity-deployment
  namespace: jkpgcityspace1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jkpgcity_web
  template:
    metadata:
      labels:
        app: jkpgcity_web
    spec:
      containers:
        - name: jkpgcityspace1
          image: localhost:5001/jkpg-city:latest
          env:
            - name: "jkpg-city"
              value: localhost:5001/jkpg-city:latest

---
apiVersion: v1
kind: Service
metadata:
  name: jkpgcity-service
  namespace: jkpgcityspace1 # Specify the desired namespace here
spec:
  selector:
    app: jkpgcityspace1
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5000
