apiVersion: apps/v1
kind: Deployment
metadata:
  name: jkpgcity-deployment
  namespace: jkpgcityspace
  labels:
    app: jkpg-city
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jkpg-city
  template:
    metadata:
      labels:
        app: jkpg-city
    spec:
      containers:
      - name: jkpg-city
      image: localhost:5000/jkpg-city:latest
---
apiVersion: v1
kind: Service
metadata:
  name: jkpgcity-service
spec:
  selector:
    app: jkpg-city
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
