apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 27017
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom: 
              secretKeyRef: 
                name: mongo-secret
                key: mongo-user
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom: 
              secretKeyRef: 
                name: mongo-secret
                key: mongo-password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom: 
              configMapKeyRef: 
                name: mongo-configmap
                key: mongo-url