apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongodbjkpg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodbjkpg
  template:
    metadata:
      labels:
        app: mongodbjkpg
    spec:
      containers:
      - name: mongodbjkpg
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef: 
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mongo-secret
              key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongodbjkpg
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000